set (CPACK_GENERATOR "TGZ")
set (CPACK_INCLUDE_TOPLEVEL_DIRECTORY "1")
set (CPACK_CMAKE_GENERATOR "Unix Makefiles")

set (CPACK_INSTALL_CMAKE_PROJECTS "./build;sayonara;ALL;/")
set (CPACK_PACKAGE_DESCRIPTION_FILE "../../MANUAL")
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Audio player and library manager")
set (CPACK_PACKAGE_EXECUTABLES "sayonara;Sayonara Player")
set (CPACK_PACKAGE_FILE_NAME "sayonara-package")
set (CPACK_PACKAGE_INSTALL_DIRECTORY "sayonara")
set (CPACK_PACKAGE_NAME "sayonara")
set (CPACK_PACKAGE_VERSION "0.3.2")
set (CPACK_PACKAGE_VERSION_MAJOR "0")
set (CPACK_PACKAGE_VERSION_MINOR "3")
set (CPACK_PACKAGE_VERSION_PATCH "2")
set (CPACK_PACKAGE_FILE_NAME "sayonara")



