#!/bin/bash


VERSIONA=`pkg-config --modversion libnotify`
MAJOR=${VERSIONA:0:1}
MINOR=${VERSIONA:2:1}

if [ $MAJOR -gt 0 ] ; then
	
	cp src/Notification/libnotify/LN_Notification.cpp.new src/Notification/libnotify/LN_Notification.cpp
else
	if [ $MINOR -gt 6 ] ; then
		echo "new libnotify version"
		cp src/Notification/libnotify/LN_Notification.cpp.new src/Notification/libnotify/LN_Notification.cpp
	else
		echo "old libnotify version"
		cp src/Notification/libnotify/LN_Notification.cpp.old src/Notification/libnotify/LN_Notification.cpp
	fi
fi

