#!/bin/bash


VERSIONA=`pkg-config --modversion libnotify`
MAJOR=${VERSIONA:0:1}
MINOR=${VERSIONA:2:1}

if [ $MAJOR -gt 0 ] ; then
	
	cp Notification/libnotify/LN_Notification.cpp.new Notification/libnotify/LN_Notification.cpp
else
	if [ $MINOR -gt 6 ] ; then
		echo "new libnotify version"
		cp Notification/libnotify/LN_Notification.cpp.new Notification/libnotify/LN_Notification.cpp
	else
		echo "old libnotify version"
		cp Notification/libnotify/LN_Notification.cpp.old Notification/libnotify/LN_Notification.cpp
	fi
fi

